server:
  port: 17610

logging:
  level:
    root: debug
    web: debug

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:  # 这里是和注册相关的配置
        namespace: 400329f6-d7a5-488d-81ad-4e13114f1532
        group: DEV # 往哪个组注册
        service: ${spring.application.name}  # 这个才是注册列表的名字 如果不写 默认是取${spring.application.name}
    gateway:
      # 定义多个路由
      routes:
        # 一个路由route的id
        - id: path_route-servicea
          # 该路由转发的目标URI
          uri: lb://service-a:17612
          # 路由条件集合
          predicates:
            - Path=/a/**
          filters:
            - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          spring-demo:
            provider: spring
            client-id: spring-gateway-demo
            client-secret: gczdNxMGMS2081TEqCx3yb0zCFX9nEn1
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:17610/login/oauth2/code/spring"
            scope: openid,ADMIN
        provider:
          spring:
            authorization-uri: http://localhost:8080/realms/spring/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/spring/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/spring/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8080/realms/spring/protocol/openid-connect/certs