server:
  port: 17610

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:  # 这里是和注册相关的配置
        namespace: 400329f6-d7a5-488d-81ad-4e13114f1532
        group: DEV # 往哪个组注册
        service: ${spring.application.name}  # 这个才是注册列表的名字 如果不写 默认是取${spring.application.name}
    gateway:
      # 定义多个路由
      routes:
        # 一个路由route的id
        - id: path_route-servicea
          # 该路由转发的目标URI
          uri: lb://service-a:17612
          # 路由条件集合
          predicates:
            - Path=/a


