version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./volumes/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: mysql
#    build:
#      context: ..
#      dockerfile: ./image/mysql/Dockerfile
    image: nacos-mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

#  seata-server:
#    image: seataio/seata-server:1.5.2
#    ports:
#      - "7091:7091"
#      - "8091:8091"
#    environment:
#      - STORE_MODE=db
#      # 以SEATA_IP作为host注册seata server
#      - SEATA_IP=seata_ip
#      - SEATA_PORT=8091
#    volumes:
#      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"        #设置系统时区
#      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"  #设置时区
#      # 假设我们通过docker cp命令把资源文件拷贝到相对路径`./seata-server/resources`中
#      # 如有问题，请阅读上面的[注意事项]以及[使用自定义配置文件]
#      - "./seata-server/resources:/seata-server/resources"