server:
  port: 17612


logging:
  level:
    root: debug
    web: debug

tomcat:
  mbeanregistry:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

#demo:
#  name: "123456"


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/spring/protocol/openid-connect/certs




