server:
  port: 17612


tomcat:
  mbeanregistry:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

#demo:
#  name: "123456"




