version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
    ports:
      - 8080:8080
    command: ["start-dev"]
    restart: always #重启docker后该容器也重启
